export const SAUDI_UNIVERSITIES = [
  "King Saud University",
  "King Abdulaziz University",
  "King Fahd University of Petroleum and Minerals",
  "Imam Abdulrahman Bin Faisal University",
  "University of Jeddah",
  "Umm Al-Qura University",
  "Islamic University of Madinah",
  "King Khalid University",
  "Qassim University",
  "Taibah University",
  "Taif University",
  "Najran University",
  "Jazan University",
  "University of Tabuk",
  "University of Hail",
  "Al-Baha University",
  "Northern Border University",
  "Imam Muhammad ibn Saud Islamic University",
  "Princess Nourah bint Abdulrahman University",
  "King Saud bin Abdulaziz University for Health Sciences",
  "Prince Sultan University",
  "Alfaisal University",
  "Effat University",
  "Dar Al-Hekma University",
] as const;
