import type {
  CommitteeEvent,
  CommitteeMember,
  CommitteeTask,
  PointHistoryItem,
  RecentActivityItem,
} from "../shared/types";

export const initialCommitteeEvents: CommitteeEvent[] = [
  {
    id: "evt-1",
    title: "Build with Gemini: Study Jam",
    type: "Workshop",
    date: "Oct 14, 2026",
    time: "4:00 PM",
    location: "King Abdullah II Hall",
    registered: 86,
    capacity: 120,
    status: "Upcoming",
    created: "Sep 18",
    updated: "Today",
    description: "Hands-on workshop exploring multimodal Gemini models and agent workflows.",
    isDraft: false,
  },
  {
    id: "evt-2",
    title: "DevFest Amman Campus Kickoff",
    type: "Conference",
    date: "Oct 27, 2026",
    time: "10:00 AM",
    location: "UJ Innovation Hub",
    registered: 142,
    capacity: 200,
    status: "Upcoming",
    created: "Sep 11",
    updated: "2h ago",
    description: "Annual campus festival uniting student developers, founders, and engineers.",
    isDraft: false,
  },
  {
    id: "evt-3",
    title: "Flutter Forward: Mobile Lab",
    type: "Workshop",
    date: "Sep 24, 2026",
    time: "3:30 PM",
    location: "Computer Lab 3",
    registered: 48,
    capacity: 50,
    status: "Completed",
    created: "Aug 30",
    updated: "Sep 25",
    description: "Building production-ready cross platform applications using Flutter.",
    isDraft: false,
  },
  {
    id: "evt-4",
    title: "Cloud Career Pathways",
    type: "Talk",
    date: "Nov 05, 2026",
    time: "5:00 PM",
    location: "Online - Google Meet",
    registered: 0,
    capacity: 100,
    status: "Draft",
    created: "Sep 29",
    updated: "Yesterday",
    description: "Discussion on cloud certifications, data engineering roles, and enterprise tech.",
    isDraft: true,
  },
  {
    id: "evt-5",
    title: "Women in Tech: Founder Stories",
    type: "Panel",
    date: "Oct 20, 2026",
    time: "2:00 PM",
    location: "Language Center",
    registered: 64,
    capacity: 100,
    status: "Needs Update",
    created: "Sep 14",
    updated: "3d ago",
    description: "Inspiring panel featuring women tech leaders sharing journeys and insights.",
    isDraft: false,
  },
];

export const initialCommitteeMembers: CommitteeMember[] = [
  {
    id: "mem-1",
    name: "Lina Saleh",
    email: "lina.saleh@uj.edu.sa",
    role: "Database Co-Lead",
    status: "Active",
    isElevated: false,
    accessExpiresAt: null,
    initials: "LS",
    avatarBgColor: "bg-sky-100 text-sky-700",
    points: 1240,
    tasksCompleted: 31,
    lastActivity: "Today, 10:42 AM",
  },
  {
    id: "mem-2",
    name: "Omar Al-Khatib",
    email: "omar.khatib@uj.edu.sa",
    role: "Data Coordinator",
    status: "Active",
    isElevated: false,
    accessExpiresAt: null,
    initials: "OA",
    avatarBgColor: "bg-emerald-100 text-emerald-700",
    points: 980,
    tasksCompleted: 24,
    lastActivity: "Yesterday",
  },
  {
    id: "mem-3",
    name: "Rama Nasser",
    email: "rama.nasser@uj.edu.sa",
    role: "Event Data Member",
    status: "Active",
    isElevated: false,
    accessExpiresAt: null,
    initials: "RN",
    avatarBgColor: "bg-purple-100 text-purple-700",
    points: 760,
    tasksCompleted: 19,
    lastActivity: "Sep 29",
  },
  {
    id: "mem-4",
    name: "Yazan Abu Rumman",
    email: "yazan.rumman@uj.edu.sa",
    role: "Database Member",
    status: "Away",
    isElevated: false,
    accessExpiresAt: null,
    initials: "YA",
    avatarBgColor: "bg-amber-100 text-amber-700",
    points: 540,
    tasksCompleted: 12,
    lastActivity: "Sep 25",
  },
  {
    id: "mem-5",
    name: "Tariq Mansoor",
    email: "tariq.mansoor@uj.edu.sa",
    role: "Data Analyst",
    status: "Active",
    isElevated: false,
    accessExpiresAt: null,
    initials: "TM",
    avatarBgColor: "bg-blue-100 text-blue-700",
    points: 620,
    tasksCompleted: 15,
    lastActivity: "Sep 28",
  },
  {
    id: "mem-6",
    name: "Huda Al-Qadi",
    email: "huda.qadi@uj.edu.sa",
    role: "Research Member",
    status: "Active",
    isElevated: false,
    accessExpiresAt: null,
    initials: "HQ",
    avatarBgColor: "bg-rose-100 text-rose-700",
    points: 490,
    tasksCompleted: 10,
    lastActivity: "Sep 27",
  },
];

export const initialCommitteeTasks: CommitteeTask[] = [
  {
    id: "task-1",
    title: "Clean and validate attendance CSV for Study Jam",
    description: "Deduplicate registration entries and verify student ID formatting.",
    assignedMemberId: "mem-3",
    assignedMemberName: "Rama Nasser",
    createdBy: "Shahad",
    dueDate: "Oct 12, 2026",
    priority: "High",
    status: "In Progress",
  },
  {
    id: "task-2",
    title: "Set up Google Meet and streaming links for Cloud Talk",
    description: "Generate recording link and confirm audio/video permissions with speaker.",
    assignedMemberId: "mem-2",
    assignedMemberName: "Omar Al-Khatib",
    createdBy: "Lina Saleh",
    dueDate: "Nov 02, 2026",
    priority: "Medium",
    status: "To Do",
  },
  {
    id: "task-3",
    title: "Compile speaker bios and slides for Women in Tech",
    description: "Gather high-resolution headshots and 100-word summaries for the brochure.",
    assignedMemberId: "mem-1",
    assignedMemberName: "Lina Saleh",
    createdBy: "Shahad",
    dueDate: "Oct 18, 2026",
    priority: "High",
    status: "In Progress",
  },
  {
    id: "task-4",
    title: "Generate post-event analytics report for Mobile Lab",
    description: "Calculate feedback scores and NPS rating from attendee surveys.",
    assignedMemberId: "mem-4",
    assignedMemberName: "Yazan Abu Rumman",
    createdBy: "Shahad",
    dueDate: "Oct 05, 2026",
    priority: "Low",
    status: "Completed",
  },
  {
    id: "task-5",
    title: "Build dashboard query for DevFest attendee check-in",
    description: "Optimize SQL query to support concurrent QR code barcode scanning.",
    assignedMemberId: "mem-5",
    assignedMemberName: "Tariq Mansoor",
    createdBy: "Lina Saleh",
    dueDate: "Oct 25, 2026",
    priority: "High",
    status: "To Do",
  },
];

export const initialRecentActivities: RecentActivityItem[] = [
  {
    id: "act-1",
    type: "event_published",
    title: "Event published",
    description: "Lina published Build with Gemini to the homepage.",
    timeAgo: "12m",
  },
  {
    id: "act-2",
    type: "details_updated",
    title: "Details updated",
    description: "Omar changed DevFest capacity from 180 to 200.",
    timeAgo: "2h",
  },
  {
    id: "act-3",
    type: "points_awarded",
    title: "Points awarded",
    description: "+80 points to Rama for attendee data cleanup.",
    timeAgo: "5h",
  },
  {
    id: "act-4",
    type: "update_requested",
    title: "Update requested",
    description: "Women in Tech is missing a final speaker bio.",
    timeAgo: "1d",
  },
];

export const initialPointHistory: PointHistoryItem[] = [
  {
    id: "ph-1",
    memberId: "mem-3",
    memberName: "Rama Nasser",
    pointsDelta: 80,
    reason: "Attendee data cleanup and validation",
    timestamp: "Today, 11:30 AM",
  },
  {
    id: "ph-2",
    memberId: "mem-1",
    memberName: "Lina Saleh",
    pointsDelta: 120,
    reason: "Speaker coordination for Study Jam",
    timestamp: "Yesterday, 4:15 PM",
  },
  {
    id: "ph-3",
    memberId: "mem-2",
    memberName: "Omar Al-Khatib",
    pointsDelta: 60,
    reason: "DevFest logistics support",
    timestamp: "Sep 28, 2026",
  },
  {
    id: "ph-4",
    memberId: "mem-5",
    memberName: "Tariq Mansoor",
    pointsDelta: 100,
    reason: "Database query optimization for QR scan",
    timestamp: "Sep 26, 2026",
  },
];

export const dataAnalysisMetricBaseline = {
  committeeMembers: 20,
  activeMembers: 16,
  awayMembers: 3,
  upcomingEvents: 5,
  upcomingEventsInNext30Days: 3,
  totalPoints: 15000,
  pointsThisMonth: 1280,
  activeTasks: 12,
  tasksDueThisWeek: 5,
  eventsCreated: 27,
  eventsPublishedThisYear: 18,
};

export const eventStatusFilterOptions = [
  { value: "Upcoming", label: "Upcoming" },
  { value: "Completed", label: "Completed" },
  { value: "Draft", label: "Draft" },
  { value: "Needs Update", label: "Needs Update" },
];

export const eventDateFilterOptions = [
  { value: "all", label: "Any date" },
  { value: "upcoming", label: "Next 30 days" },
  { value: "october", label: "October 2026" },
  { value: "november", label: "November 2026" },
];

export const eventTypeFilterOptions = [
  { value: "Workshop", label: "Workshop" },
  { value: "Conference", label: "Conference" },
  { value: "Talk", label: "Talk" },
  { value: "Panel", label: "Panel" },
];

export const dataAnalysisDashboardSeed = {
  events: initialCommitteeEvents,
  members: initialCommitteeMembers,
  tasks: initialCommitteeTasks,
  pointHistory: initialPointHistory,
  recentActivities: initialRecentActivities,
};
